language: go

env:
  - GO111MODULE=on

go:
  - "1.15.x"
  - "1.16.x"
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - go mod vendor
  - make
  - make gen
  - go test -mod vendor -race -cover -coverprofile=coverage.txt -covermode=atomic -timeout=2m ./...
  - cd ./cmd/genji && go test -race ./... && cd -
  - cd ./engine/badgerengine && go test -race ./... && cd -

after_success:
  - bash <(curl -s https://codecov.io/bash)
