language: go

env:
  - GO111MODULE=on

go:
  - '1.12.x'
  - '1.13.x'
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - go mod vendor
  - make
  - make gen
  - go test -v -mod -race -cover -timeout=2m ./...
