name: Release
on:
  push:
    branches:
      - release
      - release-v*
  workflow_dispatch:
    inputs:
      base:
        description: 'Base version'
        required: false
        default: ''
      version:
        description: 'New version'
        required: false
        default: ''

env:
  # Ensure that we have a chance to remove tags for failed release
  # before they are added to global sumdb and goproxy cache.
  GOPRIVATE: github.com/genjidb/genji
  # Enable reproducible builds.
  GOFLAGS: -trimpath
  CGO_ENABLED: '0'
  GO_EXTLINK_ENABLED: '0'

jobs:
  prepare1:
    name: Prepare genji
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.changelog.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.4
      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: prepare1-go-${{ hashFiles('**/go.sum') }}
          restore-keys: prepare1-go-
      - name: Install x/exp/cmd/gorelease
        run: go install golang.org/x/exp/cmd/gorelease@v0.0.0-20210513165259-bd7cc9f9ec66

      # Get current branch name and infer version for this release.
      #
      # Uses explicit version input if we are running on manual workflow dispatch.
      # If we are on release branch with explicit version (e.g. release-v0.13.0)
      # then branch != strip_prefix(branch, "release-") and we use branch version.
      # Otherwise use empty version and gorelease would suggest a new semantic version.
      #
      # Note that gorelease will fail if the supplied version is not a valid semantic
      # version for this release.
      #
      - name: Get version
        id: version
        env:
          base: ${{ github.event.inputs.base }}
          next: ${{ github.event.inputs.version }}
        run: |
          branch=${GITHUB_REF#refs/heads/}
          branchversion=${branch#release-}
          if [ "${next}" = "" -a "${branch}" != "${branchversion}" ]; then
            next=${branchversion}
          fi
          echo "::set-output name=base::${base}"
          echo "::set-output name=next::${next}"

      # Check github.com/genjidb/genji module.
      #
      # This step will fail if version from input is not a valid semantic version for this release.
      # We use the version suggested by gorelease tool if there is no input (workflow on push event).
      # The base version is inferred from the new version and defaults to latest release.
      #
      - name: Generate changelog
        env:
          base: ${{ steps.version.outputs.base }}
          version: ${{ steps.version.outputs.next }}
        run: |
          gorelease -base="${base}" -version="${version}" | tee changelog.txt
      - name: Extract version from changelog
        id: changelog
        run: |
          perl -n -e '
            if (s/^Suggested version: (.*)/::set-output name=version::$1/) { print }
            if (s/^(.*) is a valid semantic version for this release.$/::set-output name=version::$1/) { print }
          ' changelog.txt
      - name: Amend changelog
        run: perl -0pi -e 's/(\n.+)+\n+$//' changelog.txt
      - name: Concatenate release notes
        run: |
          if [ -f CHANGELOG.md ]; then
            cp CHANGELOG.md release.txt
          else
            touch release.txt
          fi
          echo >>release.txt
          echo --- >>release.txt
          echo >>release.txt
          cat changelog.txt >>release.txt
          echo >>release.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: release.txt
          path: release.txt
          if-no-files-found: error
          retention-days: 1

  tag1:
    name: Tag genji
    runs-on: ubuntu-latest
    needs:
      - prepare1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.4
      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: tag1-go-${{ hashFiles('**/go.sum') }}
          restore-keys: tag1-go-
      - name: Set up Git config
        run: |
          git config user.name actions-user
          git config user.email actions@github.com
      - name: Bump version
        env:
          version: ${{ needs.prepare1.outputs.version }}
        run: |
          git commit --allow-empty -m "Bump version to ${version}"
          git tag "${version}"
          git push origin "${version}"

  prepare2:
    name: Prepare badgerengine
    runs-on: ubuntu-latest
    needs:
      - prepare1
      - tag1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.4
      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: prepare2-go-${{ hashFiles('**/go.sum') }}
          restore-keys: prepare2-go-
      - name: Install x/exp/cmd/gorelease
        run: go install golang.org/x/exp/cmd/gorelease@v0.0.0-20210513165259-bd7cc9f9ec66
      - name: Drop replace directives
        working-directory: engine/badgerengine
        env:
          version: ${{ needs.prepare1.outputs.version }}
        run: |
          go mod edit -dropreplace=github.com/genjidb/genji
          go mod edit -require=github.com/genjidb/genji@"${version}"
          go mod tidy
      - name: Generate changelog
        working-directory: engine/badgerengine
        env:
          base: ${{ github.event.inputs.base }}
          version: ${{ needs.prepare1.outputs.version }}
        run: |
          gorelease -base="${base}" -version="${version}" | tee changelog.txt
      - name: Amend changelog
        working-directory: engine/badgerengine
        run: perl -0pi -e 's/(\n.+)+\n+$//' changelog.txt
      - name: Download artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: release.txt
      - name: Concatenate release notes
        run: |
          echo >>release.txt
          echo --- >>release.txt
          echo >>release.txt
          cat engine/badgerengine/changelog.txt >>release.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: release.txt
          path: release.txt
          if-no-files-found: error
          retention-days: 1

  tag2:
    name: Tag badgerengine
    runs-on: ubuntu-latest
    needs:
      - prepare1
      - prepare2
      - tag1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.4
      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: tag2-go-${{ hashFiles('**/go.sum') }}
          restore-keys: tag2-go-
      - name: Set up Git config
        run: |
          git config user.name actions-user
          git config user.email actions@github.com
      - name: Bump version
        working-directory: engine/badgerengine
        env:
          version: ${{ needs.prepare1.outputs.version }}
        run: |
          go mod edit -dropreplace=github.com/genjidb/genji
          go mod edit -require=github.com/genjidb/genji@"${version}"
          go mod tidy
          git add go.mod go.sum
          git commit --allow-empty -m "Bump version to ${version}"
          git tag engine/badgerengine/"${version}"
          git push origin engine/badgerengine/"${version}"

  tag3:
    name: Tag cmd/genji
    runs-on: ubuntu-latest
    needs:
      - prepare1
      - tag1
      - tag2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.4
      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: tag3-go-${{ hashFiles('**/go.sum') }}
          restore-keys: tag3-go-
      - name: Set up Git config
        run: |
          git config user.name actions-user
          git config user.email actions@github.com
      - name: Bump version
        working-directory: cmd/genji
        env:
          version: ${{ needs.prepare1.outputs.version }}
        run: |
          go mod edit \
            -dropreplace=github.com/genjidb/genji \
            -dropreplace=github.com/genjidb/genji/engine/badgerengine
          go mod edit \
            -require=github.com/genjidb/genji@"${version}" \
            -require=github.com/genjidb/genji/engine/badgerengine@"${version}"
          go mod tidy
          git add go.mod go.sum
          git commit --allow-empty -m "Bump version to ${version}"
          git tag cmd/genji/"${version}"
          git push origin cmd/genji/"${version}"

  draft:
    name: Create Draft
    runs-on: ubuntu-latest
    needs:
      - prepare1
      - tag1
      - tag2
      - tag3
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: release.txt
      - name: Create release
        run: gh release create --draft -R="${repo}" -t="${release_name}" -F="${body_path}" -p="${prerelease}" "${tag_name}"
        env:
          repo: ${{ github.repository }}
          release_name: ${{ needs.prepare1.outputs.version }}
          body_path: release.txt
          prerelease: ${{ contains(needs.prepare1.outputs.version, '-') }}
          tag_name: ${{ needs.prepare1.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rollback:
    name: Rollback
    runs-on: ubuntu-latest
    needs:
      - prepare1
      - tag1
      - tag2
      - tag3
      - draft
    env:
      version: ${{ needs.prepare1.outputs.version }}
    if: ${{ always() && !success() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Untag genji
        if: ${{ needs.tag1.result == 'success' }}
        run: git push origin :refs/tags/"${version}"
      - name: Untag badgerengine
        if: ${{ needs.tag2.result == 'success' }}
        run: git push origin :refs/tags/engine/badgerengine/"${version}"
      - name: Untag cmd/genji
        if: ${{ needs.tag3.result == 'success' }}
        run: git push origin :refs/tags/cmd/genji/"${version}"
